### ISSUE TITLE
Endless triggering to ngDoCheck for the component which has mat-select directive with compareWith attribute.

### ISSUE THREAD

**Issue by myatmin** [cartant/rxjs-observe#29]
Hi, I am facing above mentioned issue when using rxjs-observe with angular material on select component.

Here is the demo produced on [stackblitz](https://stackblitz.com/edit/angular-7qwemd?file=src%2Fapp%2Fapp.component.ts)

Please add the `return proxy;` in the `constructor` for the demonstration.
**Please be prepared to kill the browser** since it's circular loop!.

[Angular API doc for compareWith](https://angular.io/api/forms/SelectControlValueAccessor#caveat-option-selection)
it is being stated as below 
> Note: We listen to the 'change' event because 'input' events aren't fired for selects in Firefox and IE: https://bugzilla.mozilla.org/show_bug.cgi?id=1024350 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4660045/

Thank you! 😃

**Comment by cartant** [comment]
I've had a quick look. It's possible that the loop was effected by the proxy returning a different wrapper function for each get performed on function properties - like the `compare` method.

I've published `2.1.5` with a fix that caches the wrappers used with function properties. Maybe that might solve the problem?

**Comment by myatmin** [comment]
Yes! it's fixed! Thank you so much! 😄

**Comment by cartant** [comment]
No worries. Thanks for reporting it.
