### ISSUE TITLE
Type Definition observe.d.ts not compatible with TypeScript 2.9.2

### ISSUE THREAD

**Issue by ArgoArgus** [cartant/rxjs-observe#8]
The following error comes up with TypeScript 2.9.2 where the spread operator doesn't infer an array type from U

ERROR in node_modules/rxjs-observe/observe.d.ts(4,39): error TS2370: A rest parameter must be of an array type.

```
extends (...args: infer U)
```

**Comment by cartant** [comment]
From the README:

> TypeScript 3.0 or later is required, as the type declaration for `observe` uses [generic rest parameters](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#generic-rest-parameters).

The minimum version of TypeScript 3.0 was introduced as a breaking change in `rxjs-observe` 2.0.0.

**Comment by ArgoArgus** [comment]
Thank you very much.
